### ISSUE TITLE
split CompanyManagers into separate table

### ISSUE THREAD

**Issue by hanecak** [soit-sk/scraper-sk_company_register#3]
As of now, CompanyManagers contains information about all persons associated with the company concatenated into unstructured blob.

We would like to have more structure by splitting person into separate table and maintaining relations between companies and person in yet another table.

Crucial trick would be to identify same person based on name and address (as user in Registry) and assigning them unique ID.

**Comment by hanecak** [comment]
I've discontinued this scrapper in favor of Ekosystem.Slovensko.Digital (https://ekosystem.slovensko.digital/ , https://github.com/slovensko-digital/harvester.ecosystem), so I'm closing this as "won't fix".

**Comment by jsuchal** [comment]
<3
