### ISSUE TITLE
!!!/\/\/\!!! ERROR list index out of range !!!/\/\/\!!!

### ISSUE THREAD

**Issue by hanecak** [soit-sk/scraper-sk_company_register#5]
Scrapper now reports (on Morph.io console output) following error:

```
!!!/\/\/\!!! ERROR list index out of range !!!/\/\/\!!!
```

Investigate. Most probably regression in something comited in past two days.

**Comment by hanecak** [comment]
Still happening from time to time. Last time observed: 13.6.2016:

```
### starting work with n = 39021 and court = 0, runs so far: 21
!!!/\/\/\!!! ERROR list index out of range !!!/\/\/\!!!
```

**Comment by katkad** [comment]
you could also print url where it happened

**Comment by hanecak** [comment]
Some URLs collected via extended error logging ():

- http://www.orsr.sk/vypis.asp?lan=en&ID=11475&SID=7&P=0
- http://www.orsr.sk/vypis.asp?lan=en&ID=11394&SID=7&P=0
- http://www.orsr.sk/vypis.asp?lan=en&ID=11455&SID=7&P=0

All are retried three times and error three times. Seems like problem with the content of those (and similar) pages.

**Comment by hanecak** [comment]
I've discontinued this scrapper in favor of Ekosystem.Slovensko.Digital (https://ekosystem.slovensko.digital/), so I'm closing this as "won't fix".
